### ISSUE TITLE
headtrackr not working on Chrome 42

### ISSUE THREAD

**Issue by steren** [auduno/headtrackr#39]
http://auduno.github.io/headtrackr/examples/targets.html demo is not working on Chrome Version 42.0.2311.39 beta (64-bit)

Here is what the console is printing at the beginning:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.39 Safari/537.36 | WebGL 1.0 (OpenGL ES 2.0 Chromium) | WebKit | WebKit WebGL | WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)

In addition to a lot of warnings here is the error I get:
Could not initialise shader
VALIDATE_STATUS: false, gl error [1282]

The demo is running well on Firefox 36.0.1

**Comment by arthurmuchir** [comment]
I manage to make it work by upgrading the THREE lib version to latest version (71) and changing these lines : 
```
geometry.vertices.push( new THREE.Vertex ( new THREE.Vector3( 0, 0, -80000 )));
```
by
```
geometry.vertices.push( new THREE.Vector3( 0, 0, -80000 ) );
```

Also, to avoid warning, changing ```new THREE.PlaneGeometry```to```new THREE.PlaneBufferGeometry```

**Comment by auduno** [comment]
Sorry for the late reply to this issue. Thanks very much for reporting it and thanks to Arthur for finding the cause of the error. I updated three.js version in the examples and it seems to be working now. I used r59 instead of the latest version, since there were some changes in how wireframes are rendered after r59.
